import fs from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
import { VERIFIED_EXERCISE_MEDIA_MAP } from '../src/lib/exerciseApiService.ts';
import { WGER_EXERCISE_CATALOG } from '../src/data/exerciseCatalog.ts';

const outputDirectory = path.resolve('public/exercise-thumbnails');

const mediaUrls = new Set<string>();
for (const exercise of WGER_EXERCISE_CATALOG) {
  for (const image of exercise.images || []) {
    if (image.endsWith('.gif')) mediaUrls.add(image);
  }
}
for (const media of Object.values(VERIFIED_EXERCISE_MEDIA_MAP)) {
  if (media.gifUrl) mediaUrls.add(media.gifUrl);
}

await fs.mkdir(outputDirectory, { recursive: true });

let generated = 0;
const generatedFiles: string[] = [];
for (const imageUrl of mediaUrls) {
  const filename = path.basename(new URL(imageUrl).pathname).replace(/\.gif$/i, '.webp');
  const destination = path.join(outputDirectory, filename);

  try {
    const response = await fetch(imageUrl);
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    const source = Buffer.from(await response.arrayBuffer());

    await sharp(source, { animated: true, page: 0 })
      .resize(480, 480, { fit: 'contain', background: { r: 255, g: 255, b: 255, alpha: 1 } })
      .webp({ quality: 88, effort: 4 })
      .toFile(destination);

    generated += 1;
    generatedFiles.push(filename);
    console.log(`Generated ${filename}`);
  } catch (error) {
    console.warn(`Skipped ${imageUrl}:`, error);
  }
}

await fs.writeFile(
  path.resolve('src/data/exerciseThumbnailManifest.ts'),
  `// Generated by scripts/generateExerciseThumbnails.ts\nexport const EXERCISE_THUMBNAIL_FILES = new Set(${JSON.stringify(generatedFiles)});\n`,
  'utf8'
);

console.log(`Generated ${generated}/${mediaUrls.size} exercise thumbnails.`);
